/** Route path (URL segment) -> { title, basePath } for GenericEntityPage. Covers all 71 generic tables. */
export const ADMIN_ENTITY_ROUTES: Record<string, { title: string; basePath: string }> = {
  acdetails: { title: 'Acdetails', basePath: '/api/admin/acdetails' },
  acincome: { title: 'Ac Income', basePath: '/api/admin/acincome' },
  acldgr: { title: 'Ac Ledger', basePath: '/api/admin/acldgr' },
  acmaingroup: { title: 'Ac Main Group', basePath: '/api/admin/acmaingroup' },
  acmaintra: { title: 'Ac Main Tra', basePath: '/api/admin/acmaintra' },
  acreceived: { title: 'Ac Received', basePath: '/api/admin/acreceived' },
  acsubgroup: { title: 'Ac Subgroup', basePath: '/api/admin/acsubgroup' },
  acvchtype: { title: 'Ac Vch Type', basePath: '/api/admin/acvchtype' },
  agreement: { title: 'Agreement', basePath: '/api/admin/agreement' },
  attachments: { title: 'Attachments', basePath: '/api/admin/attachments' },
  audit: { title: 'Audit', basePath: '/api/admin/audit' },
  auditprogress: { title: 'Audit Progress', basePath: '/api/admin/auditprogress' },
  audittargetmain: { title: 'Audit Target Main', basePath: '/api/admin/audittargetmain' },
  audittargetsub: { title: 'Audit Target Sub', basePath: '/api/admin/audittargetsub' },
  'bank-names': { title: 'Bank Names', basePath: '/api/admin/bank_names' },
  bankpro: { title: 'Bank Pro', basePath: '/api/admin/bankpro' },
  bkinvestmain: { title: 'Bk Invest Main', basePath: '/api/admin/bkinvestmain' },
  bkinvestsub: { title: 'Bk Invest Sub', basePath: '/api/admin/bkinvestsub' },
  beversion: { title: 'BE Version', basePath: '/api/admin/beversion' },
  cinfo: { title: 'C Info', basePath: '/api/admin/cinfo' },
  confirmation: { title: 'Confirmation', basePath: '/api/admin/confirmation' },
  contactdatabase: { title: 'Contact Database', basePath: '/api/admin/contactdatabase' },
  converter: { title: 'Converter', basePath: '/api/admin/converter' },
  dociss: { title: 'Doc Iss', basePath: '/api/admin/dociss' },
  docrec: { title: 'Doc Rec', basePath: '/api/admin/docrec' },
  est: { title: 'Est', basePath: '/api/admin/est' },
  estcalculation: { title: 'Est Calculation', basePath: '/api/admin/estcalculation' },
  estret: { title: 'Est Ret', basePath: '/api/admin/estret' },
  fatype: { title: 'FA Type', basePath: '/api/admin/fatype' },
  feversion: { title: 'FE Version', basePath: '/api/admin/feversion' },
  fieldmain: { title: 'Field Main', basePath: '/api/admin/fieldmain' },
  fieldsub: { title: 'Field Sub', basePath: '/api/admin/fieldsub' },
  fixassets: { title: 'Fix Assets', basePath: '/api/admin/fixassets' },
  gmailadd: { title: 'Gmail Add', basePath: '/api/admin/gmailadd' },
  hdsr: { title: 'HD Serial', basePath: '/api/admin/hdsr' },
  indnote: { title: 'Ind Note', basePath: '/api/admin/indnote' },
  iroapplication: { title: 'IRO Application', basePath: '/api/admin/iroapplication' },
  itemlist: { title: 'Item List', basePath: '/api/admin/itemlist' },
  mailids: { title: 'Mail Ids', basePath: '/api/admin/mailids' },
  missmatch: { title: 'Missmatch', basePath: '/api/admin/missmatch' },
  missttype: { title: 'Misst Type', basePath: '/api/admin/missttype' },
  monthevent: { title: 'Month Event', basePath: '/api/admin/monthevent' },
  myadthap: { title: 'Myad Thap', basePath: '/api/admin/myadthap' },
  notes: { title: 'Notes', basePath: '/api/admin/notes' },
  notice: { title: 'Notice', basePath: '/api/admin/notice' },
  othercontact: { title: 'Other Contact', basePath: '/api/admin/othercontact' },
  panno: { title: 'Pan No', basePath: '/api/admin/panno' },
  partistock: { title: 'Parti Stock', basePath: '/api/admin/partistock' },
  pettycash: { title: 'Petty Cash', basePath: '/api/admin/pettycash' },
  pmtmthd: { title: 'Pmt Method', basePath: '/api/admin/pmtmthd' },
  ptmrpayment: { title: 'Ptmr Payment', basePath: '/api/admin/ptmrpayment' },
  purregd: { title: 'Pur Regd', basePath: '/api/admin/purregd' },
  purtype: { title: 'Pur Type', basePath: '/api/admin/purtype' },
  question: { title: 'Question', basePath: '/api/admin/question' },
  rights: { title: 'Rights', basePath: '/api/admin/right' },
  sales: { title: 'Sales', basePath: '/api/admin/sales' },
  servicecard: { title: 'Service Card', basePath: '/api/admin/servicecard' },
  support: { title: 'Support', basePath: '/api/admin/support' },
  target: { title: 'Target', basePath: '/api/admin/target' },
  targetvscomplete: { title: 'Target vs Complete', basePath: '/api/admin/targetvscomplete' },
  tasks: { title: 'Tasks', basePath: '/api/admin/tasks' },
  taxaccount: { title: 'Tax Account', basePath: '/api/admin/taxaccount' },
  templates: { title: 'Templates', basePath: '/api/admin/templates' },
  tockens: { title: 'Tockens', basePath: '/api/admin/tockens' },
  trate: { title: 'T Rate', basePath: '/api/admin/trate' },
  tratebus: { title: 'T Rate Bus', basePath: '/api/admin/tratebus' },
  unit: { title: 'Unit', basePath: '/api/admin/unit' },
  vatpaid: { title: 'VAT Paid', basePath: '/api/admin/vatpaid' },
  works: { title: 'Works', basePath: '/api/admin/works' },
  worktype: { title: 'Work Type', basePath: '/api/admin/worktype' },
  yesno: { title: 'Yes/No', basePath: '/api/admin/yesno' },
};
